
var listeningdata = [
    { "Title": "MCQ", "Fact": ["There are 3 options listed", "The speakers, more often than not, speak about all the 3 options", "The options are randomly mentioned and also paraphrased", "Only one answer is correct", "Usually found in section 2 and 3 of the test"], "Approach": ["In the preparation time understand the questions well", "A good understanding of the question helps you build a clear objective", "In the preparation time skim through the listed options", "While reading options look out for options that are similar in nature", "Do not listen to only get your answer, try and be with the audio", "Be proactive in terms of selection and elimination"] },
    { "Title": "Extended MCQ", "Fact": ["There are 5 options listed", "The speakers mention at least 3-4 out of them to confuse you", "The options are randomly mentioned and also paraphrased", "There are two correct answers that you have to mark", " Usually found in section 2 and 3 of the test"], "Approach": ["In the preparation time understand the question well", "A good understanding of the question helps you build a clear objective", "In the preparation time skim through the listed options", "Do not listen to only get your answer, try and be with the audio", "Be proactive in terms of selection and elimination"] },
    { "Title": "Classification", "Fact": ["There are list of options listed as A,B,C,.. and list of questions listed A,B,C,..", "The subject mentioned in the question needs to be matched to the right information", "All questions will be mentioned in a sequence", "However, the options are randomly mentioned and also paraphrased", "There is only one correct answers that you have to mark", "Multiple options will not be referred for one question, so the level of confusion would be less", "Usually found in section 2 and 3 of the test"], "Approach": ["In the preparation time read and understand the options well", "A good understanding of the options will help you match the same with the question", "All questions will be mentioned as it is and in an order, so that is not a concern", "Do not listen to only get your answer, try and be in the audio", "If you miss something, let it go"] },
    { "Title": "Map", "Fact": ["The question will have a picture of a map", "Some areas will be marked as specific reference points, while others will be reperesented by alphabets, A,B,C..", "The area marked as A,B,C.. in the map need to be matched ith the series of questions listed below", "Each question to have a single distinct answer", "An answer will never be used as a reference for some other question", "Usually found in section 2 and 3 of the test"], "Approach": ["In the preparation time, go through the map in details", "Understand your directions - North, South, East, West, Right, Left", "Prepare for the path for you to get to a particular alphabet", "Understand the placement of the alphabets in relation to the marked areas, as they will be used as refernces"] },
    { "Title": "Form/Note/Sentence/Summary/Table/Flow Chart Completion", "Fact": ["The instructions limit the answer to One/ No more than two/ No more than three words, with or without the use of a number", "Usually found in section 1 and 4 of the test"], "Approach": ["Read the questions in detail in the time given for preparation, remember preparation is the key", "Mark and underline your key words", "Predicts your likely answers while preparing", "Ensure that you connect each part of the audio to the text", "Do not be too keen on only getting the answer, this will help you control your anxiety", "Follow the key principle {Prepare, Mark and Predict} of listening, getting answers should only be the outcome of this process"] }
];

var readingdata = [{ "Title": "MCQ", "Fact": ["This type of question has 4 options listed as A,B,C,D"], "Approach": ["Read the question before you read the text", "Do not read the options at this point", "Go to the text Skim/Scan to locate the area where the possible information is. Once to get there cross verify ths same with the question and cordon off the area", "Read the cordoned area 2 times at an easy pace", "Now go to the list of options", "First eliminate the irrelevant option", "Then eliminate the contracdictory option", "Identify the possible word trap out of the remaining 2 and eliminate it", "What remains is the answer"] },
{ "Title": "Match heading to the paragraphs", "Fact": ["A heading summarises the main idea of a paragraph or section of the text", "There is a list of headings which are identified by Roman numerals (i,ii,iii,..)", "The paragraph are identified by letters (A,B,C,..)", "You must have to match the heading to the correct paragraph or section", "There will always be more headings than paragraphs or sections, so some headings will not be used", "No heading may be used more than once", "Always do this question first"], "Approach": ["Don't look at the list of heading first", "Read the paragraph in detail two times", "Don't try to analyse the paragraph after you have completed reading it itensively", "Don't try to convice yourself that you have understood everything about the paragraph by reading it repetitvely", "Now go to the list of headings and in the first round eliminate the most obvious ones", "Now see how many are you left with. If you are left with more than one heading you are probably failing for an idea trap of a word trap"] },
{ "Title": "Matching features", "Fact": ["In this type of question, you have to match pieces of information to a list of options", "It is possible that same options will not be used and that others may be used more than once"], "Approach": ["Do not read the questions or the text first", "Pick option A", "Scan for option A in the text and underline the same where ever you find it and cordon off the area", "Read the cordoned area 2 times at an easy pace", "Now go to the list of information's{question}", "Find out which information matches with details mentioned in the text", "Mark answer in front of the question in your answer booklet", "Repeat the same process for other listed options {B,C,D,...}"] },
{ "Title": "Matching information", "Fact": ["In this type of question, you have to match specific information, in the paragraphs (or sections) of a text. The paragraphs (or sections) are identified by letters (A, B, C, etc.)", "Not every paragraph (or section) may be used and some paragraphs (or sections) may be used more than once.", "The questions do not follow the order of the information in the text."], "Approach": ["Read the question first (one question only)", " Understand the question well; create a clear target in your mind with regard to what you wish to find in the listed paragraphs.", "Start reading the listed paragraphs one by one with target in mind. Since the answers are not listed in any sequence, you may read the paragraphs in any order.", "Do not do detailed/intensive reading in this part, you are not trying to figure out the core meaning of the paragraph. You are only looking for a specific piece of information. Thus target based reading is needed.", "As soon as you come across a paragraph that has the information listed, Mark the answer", "Repeat the same process for all listed questions."] },
{ "Title": "Identifying information (True/False/Not given)", "Fact": ["In this type of question, you are given a number of statements and are asked: \"Do the following statements agree with the information in the text?\"", "It is important to understand the difference between \"False\" and \"Not given\", False means that the statement contradicts the information in the text. Not given means that the statement neither agree with nor contradicts the information in the text.", " You must he careful not to use any information you already know about the topic of the test when choosing your answer.", "The answers here are listed in the same order they appear in the text.", "Don't look for words that exactly match those in the statements. You should also look for synonyms. Remember that you are matching meaning, not words."], "Approach": ["Read the question first (one question only)", "Understand the question well, have a clear understanding of the question.", "Once you have located the part of the text where your likely answer is, mark the area, Cross confirm with the question to be sure that you have located the right area.", "Now read the text with only true in your mind. If the statement in the question agree/matches with the information given in the question; mark your answer as true.", "If not, come back to the question and read it carefully. Only this time keep contradiction in your mind. Go to the same part of the text and read it carefully.", "If not, what remains is Not Given."] },
{ "Title": "Identifying information (Yes/No/Not given)", "Fact": ["It is important to understand the difference between \"No\" and \"Not given\", No means that the statement contradicts the writer's view. Not given means that the statement neither agree with nor contradicts the wrier's view.", "The answers here are listed in the same order they appear in the text."], "Approach": ["Approach is similar to True/False/Not given."] },
{ "Title": "Matching sentence endings", "Fact": ["In this type of question, you are given the one half (beginning) of a sentence as questions listed {1,2,3,..} based on information in the passage and you have to choose the best way to complete the sentence by choosing from a list of possible endings. The endings are identified by letters (A, B, C. etc.),", "There will be more sentence endings than beginnings, so you will not use all of them", "The sentence beginnings (questions) always follow the order of the text."], "Approach": ["Read the first question (The start of the sentence) One question at a time.", "Do not read the list of possible endings.", " Skim Scan to identify the part in the passage and cordon of the area where you believe the right information is.", "Read the cordoned area / areas 2 times at an easy pace.", "Now go to the list of sentence endings.", "Find out which sentence ending matches with the part you read in the text in terms of meaning.", " Once you have figured out the correct sentence ending, read the first part of the sentence (question) and the sentence ending (Option) together you check for the grammatical accuracy."] },
{ "Title": "Word from Text(Category A)", "Fact": ["Questions are as follow : Sentence Completion, Form / Note Completion, Question Answer Type", "Questions always follow the order of the text, ie, all the answers are always found in a sequence.", "Answers are always exact word/ words from the text, candidates might have to change the form of the answer"], "Approach": ["Read the question first, (One at a time)", "Understand the question well before you jump to the text.", "Skim/Scan to locate the area where the possible answer is", "On identifying the area quickly cross confirm it with the question", "Pick your answer depending upon the instruction given <br> One Word Only.<br> No more than two words {May be one word or two words}.<br> No more than three words. {May be one word, two words or three words}", "On selection of the answer perform 3 step back check strategy <br>Check the selected word for grammar in context with the question. <br>Check the selected word for logic in context with the question and the text.<br>Match the meaning of the sentence with the word as the answer to the meaning of the source area.", "Once the selected word words successfully pass these back checks, Mark the answer."] },
{ "Title": "Word from Text(Category B)", "Fact": ["Questions are as follow : Summary Completion,Map/Diagram Labelling,Flow Chart Completion,Table completion", "Questions may or may not follow the order of the text.", "Answers are always exact word/ words from the text."], "Approach": ["Approach is similar to Word from Text (Category A)"] }];



function question(module) {
    if (module == "Listening") {
        return listeningdata;
    } else {
        return readingdata;
    }
}